In [208]:
import numpy as np
import pandas as pd
import dask.dataframe as dd
#read large csv with dask

In [209]:
book = pd.read_csv("books.csv", sep = ";",error_bad_lines = False,encoding = "latin-1")

C:\Users\badol\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3457: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
b'Skipping line 6452: expected 8 fields, saw 9\nSkipping line 43667: expected 8 fields, saw 10\nSkipping line 51751: expected 8 fields, saw 9\n'
b'Skipping line 92038: expected 8 fields, saw 9\nSkipping line 104319: expected 8 fields, saw 9\nSkipping line 121768: expected 8 fields, saw 9\n'
b'Skipping line 144058: expected 8 fields, saw 9\nSkipping line 150789: expected 8 fields, saw 9\nSkipping line 157128: expected 8 fields, saw 9\nSkipping line 180189: expected 8 fields, saw 9\nSkipping line 185738: expected 8 fields, saw 9\n'
b'Skipping line 209388: expected 8 fields, saw 9\nSkipping line 220626: expected 8 fields, saw 9\nSkipping line 227933: expected 8 fields, saw 11\nSkipping line 228957: expected 8 fields, saw 10\nSkipping line 245933: expected 8 fields, saw 9\nSkipping line 251296: expected 8 fields, saw 9\nSkipping line 259941: expected 8 fields, saw 9\nSkipping line 261529: expected 8 fields, saw 9\n'
C:\Users\badol\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [210]:
print(book.shape)

(271360, 8)

In [211]:
book.drop(['Image-URL-S','Image-URL-M'],axis = 1,inplace = True)

In [212]:
book["Year-Of-Publication"].unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984, 0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, '2000', '1995', '1999', '2004',
       '2003', '1990', '1994', '1986', '1989', '2002', '1981', '1993',
       '1983', '1982', '1976', '1991', '1977', '1998', '1992', '1996',
       '0', '1997', '2001', '1974', '1968', '1987', '1984', '1988',
       '1963', '1956', '1970', '1985', '1978', '1973', '1980', '1979',
       '1975', '1969', '1961', '1965', '1939', '1958', '1950', '1953',
       '1966', '1971', '1959', '1972', '1955', '1957', '1945', '1960',
       '1967', '1932', '1924', '1964', '2012', '1911', '1927', '1948',
       '1962', '2006', '1952', '1940', '1951', '1931', '1954', '2005',
       '1930', '1941', '1944', 'DK Publishing Inc', '1943', '1938',
       '1900', '1942', '1923', '1920', '1933', 'Gallimard', '1909',
       '1946', '2008', '1378', '2030', '1936', '1947', '2011', '2020',
       '1919', '1949', '1922', '1897', '2024', '1376', '1926', '2037'],
      dtype=object)

In [213]:
book.loc[book["Year-Of-Publication"] == 'DK Publishing Inc',:]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
209538,078946697X,"DK Readers: Creating the X-Men, How It All Beg...",2000,DK Publishing Inc,http://images.amazon.com/images/P/078946697X.0...,NaN
221678,0789466953,"DK Readers: Creating the X-Men, How Comic Book...",2000,DK Publishing Inc,http://images.amazon.com/images/P/0789466953.0...,NaN

In [214]:
book.loc[book["Year-Of-Publication"] == 'Gallimard',:]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
220731,2070426769,"Peuple du ciel, suivi de 'Les Bergers\"";Jean-M...",2003,Gallimard,http://images.amazon.com/images/P/2070426769.0...,NaN

In [215]:
book = book[(book["Year-Of-Publication"] != 'DK Publishing Inc') & (book["Year-Of-Publication"] != 'Gallimard')]

In [216]:
book["Year-Of-Publication"] = book["Year-Of-Publication"].astype('int32')
book.dtypes

ISBN                   object
Book-Title             object
Book-Author            object
Year-Of-Publication     int32
Publisher              object
Image-URL-L            object
dtype: object

In [217]:
book["Publisher"].isnull().sum()

2

In [218]:
book = book.dropna(subset = ["Publisher"])

In [219]:
book["Publisher"].isnull().sum()

0

In [220]:
book["Book-Title"].isnull().sum()

0

In [221]:
book["Book-Author"].isnull().sum()

1

In [222]:
book = book.dropna(subset = ["Book-Author"])

In [223]:
book.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [224]:
book['Year-Of-Publication'] = book['Year-Of-Publication'].apply(str)

In [225]:
book.dtypes

ISBN                   object
Book-Title             object
Book-Author            object
Year-Of-Publication    object
Publisher              object
Image-URL-L            object
dtype: object

In [226]:
book["Book-Author"] = book["Book-Author"].apply(lambda x:x.split())

In [227]:
book["Book-Title"] = book["Book-Title"].apply(lambda x:x.split())

In [228]:
book["Publisher"] = book["Publisher"].apply(lambda x:x.split())

In [229]:
book['Year-Of-Publication'] = book['Year-Of-Publication'].apply(lambda x:x.split())

In [230]:
book['tags'] = book["Book-Author"] + book["Book-Title"] + book["Publisher"] + book['Year-Of-Publication']

In [231]:
book['tags'][0]

['Mark',
 'P.',
 'O.',
 'Morford',
 'Classical',
 'Mythology',
 'Oxford',
 'University',
 'Press',
 '2002']

In [232]:
book.head(1)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L,tags
0,0195153448,"[Classical, Mythology]","[Mark, P., O., Morford]",[2002],"[Oxford, University, Press]",http://images.amazon.com/images/P/0195153448.0...,"[Mark, P., O., Morford, Classical, Mythology, ..."

In [233]:
new_book = book[['ISBN','Book-Title','tags']]

In [234]:
new_book.head()

,ISBN,Book-Title,tags
0,0195153448,"[Classical, Mythology]","[Mark, P., O., Morford, Classical, Mythology, ..."
1,0002005018,"[Clara, Callan]","[Richard, Bruce, Wright, Clara, Callan, Harper..."
2,0060973129,"[Decision, in, Normandy]","[Carlo, D'Este, Decision, in, Normandy, Harper..."
3,0374157065,"[Flu:, The, Story, of, the, Great, Influenza, ...","[Gina, Bari, Kolata, Flu:, The, Story, of, the..."
4,0393045218,"[The, Mummies, of, Urumchi]","[E., J., W., Barber, The, Mummies, of, Urumchi..."

In [235]:
new_book['tags'] = new_book['tags'].apply(lambda x: " ".join(x))

C:\Users\badol\AppData\Local\Temp/ipykernel_17084/4161089345.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_book['tags'] = new_book['tags'].apply(lambda x: " ".join(x))

In [236]:
new_book['tags'][0]

'Mark P. O. Morford Classical Mythology Oxford University Press 2002'

In [237]:
new_book['tags'] = new_book['tags'].apply(lambda x:x.lower())

C:\Users\badol\AppData\Local\Temp/ipykernel_17084/3027952301.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_book['tags'] = new_book['tags'].apply(lambda x:x.lower())

In [238]:
new_book.head()

,ISBN,Book-Title,tags
0,0195153448,"[Classical, Mythology]",mark p. o. morford classical mythology oxford ...
1,0002005018,"[Clara, Callan]",richard bruce wright clara callan harperflamin...
2,0060973129,"[Decision, in, Normandy]",carlo d'este decision in normandy harperperenn...
3,0374157065,"[Flu:, The, Story, of, the, Great, Influenza, ...",gina bari kolata flu: the story of the great i...
4,0393045218,"[The, Mummies, of, Urumchi]",e. j. w. barber the mummies of urumchi w. w. n...

In [239]:
new_book['Book-Title'] = new_book['Book-Title'].apply(lambda x: " ".join(x))

C:\Users\badol\AppData\Local\Temp/ipykernel_17084/4282980574.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_book['Book-Title'] = new_book['Book-Title'].apply(lambda x: " ".join(x))

In [240]:
new_book.head()

,ISBN,Book-Title,tags
0,0195153448,Classical Mythology,mark p. o. morford classical mythology oxford ...
1,0002005018,Clara Callan,richard bruce wright clara callan harperflamin...
2,0060973129,Decision in Normandy,carlo d'este decision in normandy harperperenn...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,gina bari kolata flu: the story of the great i...
4,0393045218,The Mummies of Urumchi,e. j. w. barber the mummies of urumchi w. w. n...

In [241]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features= 2000,stop_words='english')

In [242]:
vector_book = cv.fit_transform(new_book['tags']).toarray()

In [243]:
vector_book.shape

(271354, 2000)

In [244]:
vector_book[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [245]:
cv.get_feature_names()

C:\Users\badol\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '10',
 '100',
 '101',
 '11',
 '12',
 '13',
 '14',
 '15',
 '18',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '20',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '21',
 '24',
 '2nd',
 '30',
 '3rd',
 '50',
 'ab',
 'abrams',
 'academy',
 'ace',
 'action',
 'adam',
 'adams',
 'addison',
 'adler',
 'adult',
 'advanced',
 'adventure',
 'adventures',
 'affair',
 'africa',
 'african',
 'agatha',
 'age',
 'ages',
 'ai',
 'air',
 'al',
 'aladdin',
 'alan',
 'alaska',
 'albert',
 'alex',
 'alexander',
 'alexandra',
 'alfaguara',
 'alfred',
 'algonquin',
 'alianza',
 'alice',
 'alien',
 'alison',
 'allan',
 'allen',
 'almanac',
 'alpha',
 'amanda',
 'amazing',
 'amer',
 'america',
 'american',
 'americans',
 'amour',
 'amp',
 'amy',
 'anagrama',
 'anchor',
 'ancient',
 'anderson',
 'andre',
 'andrea',
 'andrew',
 'andrews',
 'andy',
 'angel',
 'angela',
 'angels',
 'animal',
 'animals',
 'anita',
 'ann',
 'anna',
 'anne',
 'annie',
 'annual',
 'answers',
 'anthology',
 'anthony',
 'antonio',
 'apple',
 'applicable',
 'approach',
 'archer',
 'armstrong',
 'arnold',
 'arrow',
 'art',
 'arthur',
 'artist',
 'arts',
 'ashley',
 'asimov',
 'association',
 'atheneum',
 'atlantic',
 'atlas',
 'atria',
 'audio',
 'auf',
 'aus',
 'austen',
 'australia',
 'author',
 'autobiography',
 'avail',
 'avon',
 'away',
 'babies',
 'baby',
 'bad',
 'baen',
 'bailey',
 'baker',
 'ball',
 'ballantine',
 'banks',
 'bantam',
 'barbara',
 'barbour',
 'barker',
 'barnes',
 'barrett',
 'barron',
 'barry',
 'baseball',
 'based',
 'basic',
 'battle',
 'baum',
 'bay',
 'bbc',
 'beach',
 'beacon',
 'bear',
 'bears',
 'beast',
 'beatrix',
 'beautiful',
 'beauty',
 'bed',
 'bedford',
 'beginner',
 'beginners',
 'beginning',
 'behavior',
 'bell',
 'ben',
 'benjamin',
 'bennett',
 'berenstain',
 'berkley',
 'berlitz',
 'bernard',
 'berry',
 'best',
 'beth',
 'bethany',
 'betsy',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'billy',
 'biography',
 'bird',
 'birds',
 'birth',
 'bk',
 'black',
 'blair',
 'blake',
 'blaze',
 'blind',
 'block',
 'blood',
 'bloomsbury',
 'blue',
 'blues',
 'blyton',
 'board',
 'bob',
 'body',
 'bond',
 'bone',
 'bones',
 'bonnie',
 'book',
 'books',
 'born',
 'bound',
 'box',
 'boy',
 'boys',
 'bradley',
 'brain',
 'brand',
 'breaking',
 'brenda',
 'brian',
 'bride',
 'brides',
 'bridge',
 'brien',
 'bright',
 'britain',
 'british',
 'broadway',
 'broken',
 'bronte',
 'brooks',
 'brother',
 'brothers',
 'brown',
 'bruce',
 'btb',
 'buck',
 'building',
 'burke',
 'burning',
 'business',
 'butler',
 'bã',
 'ca',
 'california',
 'cambridge',
 'came',
 'cameron',
 'camp',
 'campbell',
 'canada',
 'canadian',
 'cancer',
 'candlewick',
 'card',
 'care',
 'career',
 'carey',
 'carl',
 'carlos',
 'carol',
 'carole',
 'caroline',
 'carolyn',
 'carr',
 'carroll',
 'carter',
 'cartland',
 'case',
 'castle',
 'cat',
 'catherine',
 'catholic',
 'cathy',
 'cats',
 'cd',
 'celebration',
 'celtic',
 'center',
 'century',
 'chance',
 'chandler',
 'change',
 'changing',
 'chaos',
 'chapel',
 'chapter',
 'charles',
 'charlie',
 'charlotte',
 'chase',
 'cheryl',
 'chicago',
 'chicken',
 'child',
 'childhood',
 'children',
 'childrens',
 'china',
 'chinese',
 'chocolate',
 'choice',
 'choose',
 'chris',
 'christ',
 'christian',
 'christie',
 'christina',
 'christine',
 'christmas',
 'christopher',
 'chronicle',
 'chronicles',
 'church',
 'circle',
 'citadel',
 'city',
 'civil',
 'claire',
 'clancy',
 'clare',
 'clark',
 'clarke',
 'class',
 'classic',
 'classics',
 'claudia',
 'cleary',
 'clifford',
 'cliffs',
 'clive',
 'close',
 'club',
 'coast',
 'code',
 'cohen',
 'cold',
 'cole',
 'colecciã³n',
 'colin',
 'collected',
 'collection',
 'collector',
 'college',
 'collins',
 'color',
 'columbia',
 'com',
 'come',
 'comes',
 'comics',
 'coming',
 'common',
 'communications',
 'companion',
 'company',
 'complete',
 'computer',
 'conan',
 'confessions',
 'connie',
 'connor',
 'conrad',
 'consortium',
 'constance',
 'consumer',
 'contemporaries',
 'contemporary',
 'control',
 'cook',
 'cookbook',
 'cooking',
 'cooper',
 'cornwell',
 'corp',
 'corporation',
 'country',
 'courage',
 'course',
 'court',
 'cowboy',
 'craft',
 'crafts',
 'craig',
 'crazy',
 'creating',
 'creative',
 'creek',
 'crime',
 'crimes',
 'crisis',
 'critical',
 'cross',
 'crossing',
 'crown',
 'crystal',
 'cultural',
 'culture',
 'currents',
 'curtis',
 'cycle',
 'cynthia',
 'da',
 'dad',
 'daddy',
 'dahl',
 'dailey',
 'daily',
 'dale',
 'dan',
 'dana',
 'dance',
 'dancing',
 'danger',
 'dangerous',
 'daniel',
 'danielle',
 'dark',
 'darkness',
 'das',
 'daughter',
 'daughters',
 'dave',
 'david',
 'davidson',
 'davies',
 'davis',
 'daw',
 'dawn',
 'day',
 'days',
 'dc',
 'dead',
 'deadly',
 'dean',
 'dear',
 'death',
 'debbie',
 'deborah',
 'debra',
 'deception',
 'dee',
 'deep',
 'del',
 'delacorte',
 'dell',
 'delta',
 'dem',
 'den',
 'denise',
 'dennis',
 'der',
 'des',
 'desert',
 'design',
 'desire',
 'destiny',
 'detective',
 'development',
 'devil',
 'di',
 'dial',
 'diamond',
 'diana',
 'diane',
 'diaries',
 'diary',
 'dick',
 'dickens',
 'dictionary',
 'die',
 'diet',
 'digest',
 'dinosaur',
 'dinosaurs',
 'diogenes',
 'directions',
 'discovering',
 'discovery',
 'disney',
 'dist',
 'distribooks',
 'distributed',
 'distribution',
 'division',
 'dixon',
 'dk',
 'doctor',
 'dog',
 'dogs',
 'don',
 'donald',
 'donna',
 'door',
 'doris',
 'dorling',
 'dorothy',
 'double',
 'doubleday',
 'douglas',
 'dover',
 'doyle',
 'dr',
 'dragon',
 'dragons',
 'drama',
 'dream',
 'dreams',
 'dress',
 'drew',
 'droemersche',
 'dtv',
 'du',
 'dummies',
 'duncan',
 'dunlap',
 'dunne',
 'dutton',
 'dying',
 'dã',
 'eagle',
 'earl',
 'early',
 'earth',
 'east',
 'easy',
 'eat',
 'eating',
 'ecstasy',
 'ed',
 'eden',
 'edgar',
 'edge',
 'ediciones',
 'edith',
 'edition',
 'editions',
 'editores',
 'editorial',
 'editors',
 'education',
 'educational',
 'edward',
 'edwards',
 'egmont',
 'eileen',
 'ein',
 'eine',
 'el',
 'elaine',
 'eleanor',
 'element',
 'eliot',
 'elizabeth',
 'ellen',
 'ellis',
 'emily',
 'emma',
 'empire',
 'en',
 'encyclopedia',
 'end',
 'enemy',
 'england',
 'english',
 'enid',
 'entertainment',
 'eos',
 'eric',
 'ernest',
 'erzã',
 'es',
 'escape',
 'essays',
 'essential',
 'et',
 'eugene',
 'europe',
 'european',
 'eva',
 'evans',
 'eve',
 'evelyn',
 'everyday',
 'everyman',
 'evil',
 'evolution',
 'experience',
 'exploring',
 'extraordinary',
 'eye',
 'eyes',
 'eyewitness',
 'faber',
 'face',
 'facts',
 'fair',
 'fairy',
 'faith',
 'fall',
 'families',
 'family',
 'famous',
 'fantasy',
 'far',
 'farm',
 'farmer',
 'farrar',
 'fast',
 'fat',
 'father',
 'favorite',
 'fawcett',
 'fear',
 'fern',
 'fiction',
 'field',
 'file',
 'files',
 'film',
 'final',
 'financial',
 'finding',
 'fine',
 'firefly',
 'fireside',
 'fischer',
 'fish',
 'fisher',
 'fitzgerald',
 'flame',
 'flammarion',
 'fleming',
 'flight',
 'flowers',
 'fly',
 'flying',
 'fodor',
 'food',
 'forbidden',
 'force',
 'ford',
 'foreign',
 'forest',
 'forever',
 'forge',
 'forgotten',
 'fortune',
 'foster',
 'foundation',
 'fourth',
 'fox',
 'france',
 'frances',
 'francine',
 'francis',
 'francisco',
 'frank',
 'frankfurt',
 'franklin',
 'franz',
 'fraser',
 'fred',
 'frederick',
 'free',
 'freedom',
 'freeman',
 'french',
 'friedman',
 'friend',
 'friends',
 'friendship',
 'frommer',
 'frontier',
 'fun',
 'future',
 'fã',
 'gabriel',
 'gail',
 'gallimard',
 'game',
 'games',
 'garcia',
 'garden',
 'gardening',
 'gardens',
 'gardner',
 'garfield',
 'gary',
 'gate',
 'gay',
 'gene',
 'general',
 'generation',
 'geoffrey',
 'geographic',
 'george',
 'georges',
 'georgia',
 'gerald',
 'german',
 'getting',
 'ghost',
 'ghosts',
 'giant',
 'gift',
 'gifts',
 'gilbert',
 'girl',
 'girls',
 'giroux',
 'glass',
 'global',
 'globe',
 'gloria',
 'glory',
 'gmbh',
 'god',
 'goddess',
 'gods',
 'goes',
 'going',
 'gold',
 'golden',
 'goldmann',
 'gone',
 'good',
 'goosebumps',
 'gordon',
 'gospel',
 'got',
 'grace',
 'grade',
 'graf',
 'graham',
 'gramercy',
 'grand',
 'grant',
 'graphic',
 'gray',
 'great',
 'greatest',
 'greek',
 'green',
 'greenberg',
 'greene',
 'greg',
 'gregory',
 'grey',
 'griffin',
 'grosset',
 'ground',
 'group',
 'grove',
 'growing',
 'guide',
 'guides',
 'guptill',
 'guy',
 'gã',
 'half',
 'hall',
 'hamilton',
 'hand',
 'handbook',
 'hands',
 'hannah',
 'hans',
 'happiness',
 'happy',
 'harcourt',
 'hard',
 'hardcover',
 'hardy',
 'harlequin',
 'harmony',
 'harold',
 'harper',
 'harpercollins',
 'harperentertainment',
 'harperresource',
 'harpersanfrancisco',
 'harpertorch',
 'harpertrophy',
 'harriet',
 'harris',
 'harrison',
 'harry',
 'hart',
 'harvard',
 'harvest',
 'harvey',
 'haunted',
 'hawthorne',
 'hay',
 'head',
 'headline',
 'healing',
 'health',
 'healthy',
 'heart',
 'hearts',
 'heat',
 'heather',
 'heaven',
 'heinemann',
 'helen',
 'hell',
 'hello',
 'help',
 'henry',
 'herbert',
 'heritage',
 'herman',
 'hero',
 'heroes',
 'heyne',
 'hidden',
 'higgins',
 'high',
 'hill',
 'hills',
 'historical',
 'history',
 'hodder',
 'hoffman',
 'holiday',
 'hollywood',
 'holmes',
 'holt',
 'holy',
 'home',
 'homes',
 'honor',
 'hope',
 'hopkins',
 'horror',
 'horse',
 'hot',
 'houghton',
 'hour',
 'hours',
 'house',
 'howard',
 'hudson',
 'hugh',
 'hughes',
 'human',
 'hunt',
 'hunter',
 'husband',
 'hyperion',
 'ian',
 'ice',
 'ich',
 'ideas',
 'idiot',
 'ii',
 'iii',
 'il',
 'illustrated',
 'im',
 'image',
 'incorporated',
 'independent',
 'indian',
 'indiana',
 'information',
 'ink',
 'inner',
 'inside',
 'inspector',
 'inspired',
 'institute',
 'international',
 'internet',
 'intimate',
 'intl',
 'intrigue',
 'introduction',
 'ireland',
 'irene',
 'iris',
 'irish',
 'iron',
 'irving',
 'isaac',
 'isabel',
 'island',
 'italian',
 'ivy',
 'jack',
 'jackie',
 'jackson',
 'jacqueline',
 'jacques',
 'james',
 'jan',
 'jane',
 'janes',
 'janet',
 'janice',
 'japan',
 'japanese',
 'jay',
 'jayne',
 'jean',
 'jeanne',
 'jeff',
 'jeffrey',
 'jenkins',
 'jennifer',
 'jenny',
 'jensen',
 'jeremy',
 'jerry',
 'jessica',
 'jesus',
 'jewish',
 'jill',
 'jim',
 'jo',
 'joan',
 'joanna',
 'joanne',
 'job',
 'joe',
 'joel',
 'john',
 'johnson',
 'johnston',
 'jokes',
 'jon',
 'jonathan',
 'jones',
 'jordan',
 'jose',
 'joseph',
 'journal',
 'journey',
 'journeys',
 'jove',
 'joy',
 'joyce',
 'jr',
 'juan',
 'jude',
 'judith',
 'judy',
 'jules',
 'julia',
 'julian',
 'julie',
 'june',
 'junior',
 'just',
 'justice',
 'juvenile',
 'karen',
 'karl',
 'kate',
 'katherine',
 'kathleen',
 'kathryn',
 'kathy',
 'kay',
 'kaye',
 'keene',
 'keith',
 ...]

In [246]:
# using steming to get {dance,dancing,danced} to {danc,dance,dance}
#nltk library

In [247]:
import nltk

In [248]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [249]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
     
    return " ".join(y)

In [250]:
new_book['tags'].apply(stem)

0         mark p. o. morford classic mytholog oxford uni...
1         richard bruce wright clara callan harperflamin...
2          carlo d'est decis in normandi harperperenni 1991
3         gina bari kolata flu: the stori of the great i...
4         e. j. w. barber the mummi of urumchi w. w. nor...
                                ...
271355    paula danzig there' a bat in bunk five random ...
271356    teri sloat from one to one hundr dutton book 1991
271357    christin wicker lili dale : the true stori of ...
271358    plato republ (world' classics) oxford univers ...
271359    christoph biffl a guid tour of rene descartes'...
Name: tags, Length: 271354, dtype: object

In [252]:
cv.get_feature_names()

['000',
 '10',
 '100',
 '101',
 '11',
 '12',
 '13',
 '14',
 '15',
 '18',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '20',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '21',
 '24',
 '2nd',
 '30',
 '3rd',
 '50',
 'ab',
 'abrams',
 'academy',
 'ace',
 'action',
 'adam',
 'adams',
 'addison',
 'adler',
 'adult',
 'advanced',
 'adventure',
 'adventures',
 'affair',
 'africa',
 'african',
 'agatha',
 'age',
 'ages',
 'ai',
 'air',
 'al',
 'aladdin',
 'alan',
 'alaska',
 'albert',
 'alex',
 'alexander',
 'alexandra',
 'alfaguara',
 'alfred',
 'algonquin',
 'alianza',
 'alice',
 'alien',
 'alison',
 'allan',
 'allen',
 'almanac',
 'alpha',
 'amanda',
 'amazing',
 'amer',
 'america',
 'american',
 'americans',
 'amour',
 'amp',
 'amy',
 'anagrama',
 'anchor',
 'ancient',
 'anderson',
 'andre',
 'andrea',
 'andrew',
 'andrews',
 'andy',
 'angel',
 'angela',
 'angels',
 'animal',
 'animals',
 'anita',
 'ann',
 'anna',
 'anne',
 'annie',
 'annual',
 'answers',
 'anthology',
 'anthony',
 'antonio',
 'apple',
 'applicable',
 'approach',
 'archer',
 'armstrong',
 'arnold',
 'arrow',
 'art',
 'arthur',
 'artist',
 'arts',
 'ashley',
 'asimov',
 'association',
 'atheneum',
 'atlantic',
 'atlas',
 'atria',
 'audio',
 'auf',
 'aus',
 'austen',
 'australia',
 'author',
 'autobiography',
 'avail',
 'avon',
 'away',
 'babies',
 'baby',
 'bad',
 'baen',
 'bailey',
 'baker',
 'ball',
 'ballantine',
 'banks',
 'bantam',
 'barbara',
 'barbour',
 'barker',
 'barnes',
 'barrett',
 'barron',
 'barry',
 'baseball',
 'based',
 'basic',
 'battle',
 'baum',
 'bay',
 'bbc',
 'beach',
 'beacon',
 'bear',
 'bears',
 'beast',
 'beatrix',
 'beautiful',
 'beauty',
 'bed',
 'bedford',
 'beginner',
 'beginners',
 'beginning',
 'behavior',
 'bell',
 'ben',
 'benjamin',
 'bennett',
 'berenstain',
 'berkley',
 'berlitz',
 'bernard',
 'berry',
 'best',
 'beth',
 'bethany',
 'betsy',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'billy',
 'biography',
 'bird',
 'birds',
 'birth',
 'bk',
 'black',
 'blair',
 'blake',
 'blaze',
 'blind',
 'block',
 'blood',
 'bloomsbury',
 'blue',
 'blues',
 'blyton',
 'board',
 'bob',
 'body',
 'bond',
 'bone',
 'bones',
 'bonnie',
 'book',
 'books',
 'born',
 'bound',
 'box',
 'boy',
 'boys',
 'bradley',
 'brain',
 'brand',
 'breaking',
 'brenda',
 'brian',
 'bride',
 'brides',
 'bridge',
 'brien',
 'bright',
 'britain',
 'british',
 'broadway',
 'broken',
 'bronte',
 'brooks',
 'brother',
 'brothers',
 'brown',
 'bruce',
 'btb',
 'buck',
 'building',
 'burke',
 'burning',
 'business',
 'butler',
 'bã',
 'ca',
 'california',
 'cambridge',
 'came',
 'cameron',
 'camp',
 'campbell',
 'canada',
 'canadian',
 'cancer',
 'candlewick',
 'card',
 'care',
 'career',
 'carey',
 'carl',
 'carlos',
 'carol',
 'carole',
 'caroline',
 'carolyn',
 'carr',
 'carroll',
 'carter',
 'cartland',
 'case',
 'castle',
 'cat',
 'catherine',
 'catholic',
 'cathy',
 'cats',
 'cd',
 'celebration',
 'celtic',
 'center',
 'century',
 'chance',
 'chandler',
 'change',
 'changing',
 'chaos',
 'chapel',
 'chapter',
 'charles',
 'charlie',
 'charlotte',
 'chase',
 'cheryl',
 'chicago',
 'chicken',
 'child',
 'childhood',
 'children',
 'childrens',
 'china',
 'chinese',
 'chocolate',
 'choice',
 'choose',
 'chris',
 'christ',
 'christian',
 'christie',
 'christina',
 'christine',
 'christmas',
 'christopher',
 'chronicle',
 'chronicles',
 'church',
 'circle',
 'citadel',
 'city',
 'civil',
 'claire',
 'clancy',
 'clare',
 'clark',
 'clarke',
 'class',
 'classic',
 'classics',
 'claudia',
 'cleary',
 'clifford',
 'cliffs',
 'clive',
 'close',
 'club',
 'coast',
 'code',
 'cohen',
 'cold',
 'cole',
 'colecciã³n',
 'colin',
 'collected',
 'collection',
 'collector',
 'college',
 'collins',
 'color',
 'columbia',
 'com',
 'come',
 'comes',
 'comics',
 'coming',
 'common',
 'communications',
 'companion',
 'company',
 'complete',
 'computer',
 'conan',
 'confessions',
 'connie',
 'connor',
 'conrad',
 'consortium',
 'constance',
 'consumer',
 'contemporaries',
 'contemporary',
 'control',
 'cook',
 'cookbook',
 'cooking',
 'cooper',
 'cornwell',
 'corp',
 'corporation',
 'country',
 'courage',
 'course',
 'court',
 'cowboy',
 'craft',
 'crafts',
 'craig',
 'crazy',
 'creating',
 'creative',
 'creek',
 'crime',
 'crimes',
 'crisis',
 'critical',
 'cross',
 'crossing',
 'crown',
 'crystal',
 'cultural',
 'culture',
 'currents',
 'curtis',
 'cycle',
 'cynthia',
 'da',
 'dad',
 'daddy',
 'dahl',
 'dailey',
 'daily',
 'dale',
 'dan',
 'dana',
 'dance',
 'dancing',
 'danger',
 'dangerous',
 'daniel',
 'danielle',
 'dark',
 'darkness',
 'das',
 'daughter',
 'daughters',
 'dave',
 'david',
 'davidson',
 'davies',
 'davis',
 'daw',
 'dawn',
 'day',
 'days',
 'dc',
 'dead',
 'deadly',
 'dean',
 'dear',
 'death',
 'debbie',
 'deborah',
 'debra',
 'deception',
 'dee',
 'deep',
 'del',
 'delacorte',
 'dell',
 'delta',
 'dem',
 'den',
 'denise',
 'dennis',
 'der',
 'des',
 'desert',
 'design',
 'desire',
 'destiny',
 'detective',
 'development',
 'devil',
 'di',
 'dial',
 'diamond',
 'diana',
 'diane',
 'diaries',
 'diary',
 'dick',
 'dickens',
 'dictionary',
 'die',
 'diet',
 'digest',
 'dinosaur',
 'dinosaurs',
 'diogenes',
 'directions',
 'discovering',
 'discovery',
 'disney',
 'dist',
 'distribooks',
 'distributed',
 'distribution',
 'division',
 'dixon',
 'dk',
 'doctor',
 'dog',
 'dogs',
 'don',
 'donald',
 'donna',
 'door',
 'doris',
 'dorling',
 'dorothy',
 'double',
 'doubleday',
 'douglas',
 'dover',
 'doyle',
 'dr',
 'dragon',
 'dragons',
 'drama',
 'dream',
 'dreams',
 'dress',
 'drew',
 'droemersche',
 'dtv',
 'du',
 'dummies',
 'duncan',
 'dunlap',
 'dunne',
 'dutton',
 'dying',
 'dã',
 'eagle',
 'earl',
 'early',
 'earth',
 'east',
 'easy',
 'eat',
 'eating',
 'ecstasy',
 'ed',
 'eden',
 'edgar',
 'edge',
 'ediciones',
 'edith',
 'edition',
 'editions',
 'editores',
 'editorial',
 'editors',
 'education',
 'educational',
 'edward',
 'edwards',
 'egmont',
 'eileen',
 'ein',
 'eine',
 'el',
 'elaine',
 'eleanor',
 'element',
 'eliot',
 'elizabeth',
 'ellen',
 'ellis',
 'emily',
 'emma',
 'empire',
 'en',
 'encyclopedia',
 'end',
 'enemy',
 'england',
 'english',
 'enid',
 'entertainment',
 'eos',
 'eric',
 'ernest',
 'erzã',
 'es',
 'escape',
 'essays',
 'essential',
 'et',
 'eugene',
 'europe',
 'european',
 'eva',
 'evans',
 'eve',
 'evelyn',
 'everyday',
 'everyman',
 'evil',
 'evolution',
 'experience',
 'exploring',
 'extraordinary',
 'eye',
 'eyes',
 'eyewitness',
 'faber',
 'face',
 'facts',
 'fair',
 'fairy',
 'faith',
 'fall',
 'families',
 'family',
 'famous',
 'fantasy',
 'far',
 'farm',
 'farmer',
 'farrar',
 'fast',
 'fat',
 'father',
 'favorite',
 'fawcett',
 'fear',
 'fern',
 'fiction',
 'field',
 'file',
 'files',
 'film',
 'final',
 'financial',
 'finding',
 'fine',
 'firefly',
 'fireside',
 'fischer',
 'fish',
 'fisher',
 'fitzgerald',
 'flame',
 'flammarion',
 'fleming',
 'flight',
 'flowers',
 'fly',
 'flying',
 'fodor',
 'food',
 'forbidden',
 'force',
 'ford',
 'foreign',
 'forest',
 'forever',
 'forge',
 'forgotten',
 'fortune',
 'foster',
 'foundation',
 'fourth',
 'fox',
 'france',
 'frances',
 'francine',
 'francis',
 'francisco',
 'frank',
 'frankfurt',
 'franklin',
 'franz',
 'fraser',
 'fred',
 'frederick',
 'free',
 'freedom',
 'freeman',
 'french',
 'friedman',
 'friend',
 'friends',
 'friendship',
 'frommer',
 'frontier',
 'fun',
 'future',
 'fã',
 'gabriel',
 'gail',
 'gallimard',
 'game',
 'games',
 'garcia',
 'garden',
 'gardening',
 'gardens',
 'gardner',
 'garfield',
 'gary',
 'gate',
 'gay',
 'gene',
 'general',
 'generation',
 'geoffrey',
 'geographic',
 'george',
 'georges',
 'georgia',
 'gerald',
 'german',
 'getting',
 'ghost',
 'ghosts',
 'giant',
 'gift',
 'gifts',
 'gilbert',
 'girl',
 'girls',
 'giroux',
 'glass',
 'global',
 'globe',
 'gloria',
 'glory',
 'gmbh',
 'god',
 'goddess',
 'gods',
 'goes',
 'going',
 'gold',
 'golden',
 'goldmann',
 'gone',
 'good',
 'goosebumps',
 'gordon',
 'gospel',
 'got',
 'grace',
 'grade',
 'graf',
 'graham',
 'gramercy',
 'grand',
 'grant',
 'graphic',
 'gray',
 'great',
 'greatest',
 'greek',
 'green',
 'greenberg',
 'greene',
 'greg',
 'gregory',
 'grey',
 'griffin',
 'grosset',
 'ground',
 'group',
 'grove',
 'growing',
 'guide',
 'guides',
 'guptill',
 'guy',
 'gã',
 'half',
 'hall',
 'hamilton',
 'hand',
 'handbook',
 'hands',
 'hannah',
 'hans',
 'happiness',
 'happy',
 'harcourt',
 'hard',
 'hardcover',
 'hardy',
 'harlequin',
 'harmony',
 'harold',
 'harper',
 'harpercollins',
 'harperentertainment',
 'harperresource',
 'harpersanfrancisco',
 'harpertorch',
 'harpertrophy',
 'harriet',
 'harris',
 'harrison',
 'harry',
 'hart',
 'harvard',
 'harvest',
 'harvey',
 'haunted',
 'hawthorne',
 'hay',
 'head',
 'headline',
 'healing',
 'health',
 'healthy',
 'heart',
 'hearts',
 'heat',
 'heather',
 'heaven',
 'heinemann',
 'helen',
 'hell',
 'hello',
 'help',
 'henry',
 'herbert',
 'heritage',
 'herman',
 'hero',
 'heroes',
 'heyne',
 'hidden',
 'higgins',
 'high',
 'hill',
 'hills',
 'historical',
 'history',
 'hodder',
 'hoffman',
 'holiday',
 'hollywood',
 'holmes',
 'holt',
 'holy',
 'home',
 'homes',
 'honor',
 'hope',
 'hopkins',
 'horror',
 'horse',
 'hot',
 'houghton',
 'hour',
 'hours',
 'house',
 'howard',
 'hudson',
 'hugh',
 'hughes',
 'human',
 'hunt',
 'hunter',
 'husband',
 'hyperion',
 'ian',
 'ice',
 'ich',
 'ideas',
 'idiot',
 'ii',
 'iii',
 'il',
 'illustrated',
 'im',
 'image',
 'incorporated',
 'independent',
 'indian',
 'indiana',
 'information',
 'ink',
 'inner',
 'inside',
 'inspector',
 'inspired',
 'institute',
 'international',
 'internet',
 'intimate',
 'intl',
 'intrigue',
 'introduction',
 'ireland',
 'irene',
 'iris',
 'irish',
 'iron',
 'irving',
 'isaac',
 'isabel',
 'island',
 'italian',
 'ivy',
 'jack',
 'jackie',
 'jackson',
 'jacqueline',
 'jacques',
 'james',
 'jan',
 'jane',
 'janes',
 'janet',
 'janice',
 'japan',
 'japanese',
 'jay',
 'jayne',
 'jean',
 'jeanne',
 'jeff',
 'jeffrey',
 'jenkins',
 'jennifer',
 'jenny',
 'jensen',
 'jeremy',
 'jerry',
 'jessica',
 'jesus',
 'jewish',
 'jill',
 'jim',
 'jo',
 'joan',
 'joanna',
 'joanne',
 'job',
 'joe',
 'joel',
 'john',
 'johnson',
 'johnston',
 'jokes',
 'jon',
 'jonathan',
 'jones',
 'jordan',
 'jose',
 'joseph',
 'journal',
 'journey',
 'journeys',
 'jove',
 'joy',
 'joyce',
 'jr',
 'juan',
 'jude',
 'judith',
 'judy',
 'jules',
 'julia',
 'julian',
 'julie',
 'june',
 'junior',
 'just',
 'justice',
 'juvenile',
 'karen',
 'karl',
 'kate',
 'katherine',
 'kathleen',
 'kathryn',
 'kathy',
 'kay',
 'kaye',
 'keene',
 'keith',
 ...]

In [253]:
from sklearn.metrics.pairwise import cosine_similarity

In [254]:
cosine_similarity(vector_book)

MemoryError: Unable to allocate 4.04 GiB for an array with shape (271354, 2000) and data type float64